default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_devise_token_seed_development
  name: YOUR_CUSTOM_USERNAME
  password: YOUR_PASSWORD
test:
  <<: *default
  database: rails_devise_token_seed_test
  name: YOUR_CUSTOM_USERNAME
  password: YOUR_PASSWORD

production:
  <<: *default
  database: travel_production
  name: travel
  password: <%= ENV['TRAVEL_DATABASE_PASSWORD'] %>
